### ISSUE TITLE
Fix import collision: github.com/Sirupsen/logrus

### ISSUE THREAD

**Issue by ashokrajar** [akamai-open/AkamaiOPEN-edgegrid-golang#2]
Getting import collision when using

case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

Go Environment:

go version go1.7.1 darwin/amd64
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xf/zmmkj8k17lg8cv8hny0h7k8m0000gn/T/go-build046404517=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by bscott** [comment]
I'm now getting this error with latest
